import { ToolsCreateMigrationTemplateInput } from '@api/graphql';

export const migrations: ToolsCreateMigrationTemplateInput[] = [
    /* {
        id      : '1cd0c79e-b83b-4ebf-b112-063669703cdc',
        name    : 'IAM Permissions',
        version : 'v1.0.0',
        sort    : 1,
        upScript: `
INSERT INTO public."IamPermission" (id, "name", "boundedContextId")
VALUES('752a72f1-940d-49f7-9702-44f7b95a7ff5'::uuid, 'aurora.test', 'f405132f-786d-4a6a-a262-0e6a6518aec3'::uuid);
        `,
        downScript: `
DELETE FROM public."IamPermission"
WHERE id='752a72f1-940d-49f7-9702-44f7b95a7ff5'::uuid;
        `,
    }, */
    {
        id      : '296402f5-8dd4-408e-a61f-14eac11f10e1',
        name    : 'Add rowId to IamAccount',
        version : '0.0.1',
        sort    : 1,
        upScript: `
            ALTER TABLE public."IamAccount" ADD COLUMN "rowId" BIGINT GENERATED BY DEFAULT AS IDENTITY;

            WITH ordered AS (
                SELECT id AS uuid_pk, ROW_NUMBER() OVER (ORDER BY "createdAt", id) AS rn FROM public."IamAccount"
            )
            UPDATE public."IamAccount" t
                SET "rowId" = o.rn
            FROM ordered o
                WHERE t.id = o.uuid_pk
                    AND t."rowId" IS NULL;

            SELECT setval(pg_get_serial_sequence('public."IamAccount"','rowId'), (SELECT MAX("rowId") FROM public."IamAccount"), true);

            ALTER TABLE public."IamAccount" ALTER COLUMN "rowId" SET NOT NULL;
            CREATE UNIQUE INDEX iam_account_row_id ON public."IamAccount" USING btree ("rowId");
        `,
        downScript: `
            DROP INDEX IF EXISTS "iam_account_row_id";
            ALTER TABLE public."IamAccount" DROP COLUMN IF EXISTS "rowId";
        `,
    },
    {
        id      : '3d246816-dcf7-4c62-8d95-6a95c4c87030',
        name    : 'Add rowId to IamBoundedContext',
        version : '0.0.1',
        sort    : 2,
        upScript: `
            ALTER TABLE public."IamBoundedContext" ADD COLUMN "rowId" BIGINT GENERATED BY DEFAULT AS IDENTITY;

            WITH ordered AS (
                SELECT id AS uuid_pk, ROW_NUMBER() OVER (ORDER BY "createdAt", id) AS rn FROM public."IamBoundedContext"
            )
            UPDATE public."IamBoundedContext" t
                SET "rowId" = o.rn
            FROM ordered o
                WHERE t.id = o.uuid_pk
                    AND t."rowId" IS NULL;

            SELECT setval(pg_get_serial_sequence('public."IamBoundedContext"','rowId'), (SELECT MAX("rowId") FROM public."IamBoundedContext"), true);

            ALTER TABLE public."IamBoundedContext" ALTER COLUMN "rowId" SET NOT NULL;
            CREATE UNIQUE INDEX iam_bounded_context_row_id ON public."IamBoundedContext" USING btree ("rowId");
        `,
        downScript: `
            DROP INDEX IF EXISTS "iam_bounded_context_row_id";
            ALTER TABLE public."IamBoundedContext" DROP COLUMN IF EXISTS "rowId";
        `,
    },
    {
        id      : '10041006-56df-4dbd-849e-7ca590e59106',
        name    : 'Add rowId to IamPermission',
        version : '0.0.1',
        sort    : 3,
        upScript: `
            ALTER TABLE public."IamPermission" ADD COLUMN "rowId" BIGINT GENERATED BY DEFAULT AS IDENTITY;

            WITH ordered AS (
                SELECT id AS uuid_pk, ROW_NUMBER() OVER (ORDER BY "createdAt", id) AS rn FROM public."IamPermission"
            )
            UPDATE public."IamPermission" t
                SET "rowId" = o.rn
            FROM ordered o
                WHERE t.id = o.uuid_pk
                    AND t."rowId" IS NULL;

            SELECT setval(pg_get_serial_sequence('public."IamPermission"','rowId'), (SELECT MAX("rowId") FROM public."IamPermission"), true);

            ALTER TABLE public."IamPermission" ALTER COLUMN "rowId" SET NOT NULL;
            CREATE UNIQUE INDEX iam_permission_row_id ON public."IamPermission" USING btree ("rowId");
        `,
        downScript: `
            DROP INDEX IF EXISTS "iam_permission_row_id";
            ALTER TABLE public."IamPermission" DROP COLUMN IF EXISTS "rowId";
        `,
    },
    {
        id      : 'ed53e667-ad29-4054-827d-4bd135b26b59',
        name    : 'Add rowId to IamRole',
        version : '0.0.1',
        sort    : 4,
        upScript: `
            ALTER TABLE public."IamRole" ADD COLUMN "rowId" BIGINT GENERATED BY DEFAULT AS IDENTITY;

            WITH ordered AS (
                SELECT id AS uuid_pk, ROW_NUMBER() OVER (ORDER BY "createdAt", id) AS rn FROM public."IamRole"
            )
            UPDATE public."IamRole" t
                SET "rowId" = o.rn
            FROM ordered o
                WHERE t.id = o.uuid_pk
                    AND t."rowId" IS NULL;

            SELECT setval(pg_get_serial_sequence('public."IamRole"','rowId'), (SELECT MAX("rowId") FROM public."IamRole"), true);

            ALTER TABLE public."IamRole" ALTER COLUMN "rowId" SET NOT NULL;
            CREATE UNIQUE INDEX iam_role_row_id ON public."IamRole" USING btree ("rowId");
        `,
        downScript: `
            DROP INDEX IF EXISTS "iam_role_row_id";
            ALTER TABLE public."IamRole" DROP COLUMN IF EXISTS "rowId";
        `,
    },
    {
        id      : '2d71ab42-f073-4772-9fbb-22f4ee6e1178',
        name    : 'Add rowId to IamTag',
        version : '0.0.1',
        sort    : 5,
        upScript: `
            ALTER TABLE public."IamTag" ADD COLUMN "rowId" BIGINT GENERATED BY DEFAULT AS IDENTITY;

            WITH ordered AS (
                SELECT id AS uuid_pk, ROW_NUMBER() OVER (ORDER BY "createdAt", id) AS rn FROM public."IamTag"
            )
            UPDATE public."IamTag" t
                SET "rowId" = o.rn
            FROM ordered o
                WHERE t.id = o.uuid_pk
                    AND t."rowId" IS NULL;

            SELECT setval(pg_get_serial_sequence('public."IamTag"','rowId'), (SELECT MAX("rowId") FROM public."IamTag"), true);

            ALTER TABLE public."IamTag" ALTER COLUMN "rowId" SET NOT NULL;
            CREATE UNIQUE INDEX iam_tag_row_id ON public."IamTag" USING btree ("rowId");
        `,
        downScript: `
            DROP INDEX IF EXISTS "iam_tag_row_id";
            ALTER TABLE public."IamTag" DROP COLUMN IF EXISTS "rowId";
        `,
    },
    {
        id      : 'e82358c0-cfa1-449f-90b8-ca664c4195ca',
        name    : 'Add rowId to IamTenant',
        version : '0.0.1',
        sort    : 6,
        upScript: `
            ALTER TABLE public."IamTenant" ADD COLUMN "rowId" BIGINT GENERATED BY DEFAULT AS IDENTITY;

            WITH ordered AS (
                SELECT id AS uuid_pk, ROW_NUMBER() OVER (ORDER BY "createdAt", id) AS rn FROM public."IamTenant"
            )
            UPDATE public."IamTenant" t
                SET "rowId" = o.rn
            FROM ordered o
                WHERE t.id = o.uuid_pk
                    AND t."rowId" IS NULL;

            SELECT setval(pg_get_serial_sequence('public."IamTenant"','rowId'), (SELECT MAX("rowId") FROM public."IamTenant"), true);

            ALTER TABLE public."IamTenant" ALTER COLUMN "rowId" SET NOT NULL;
            CREATE UNIQUE INDEX iam_tenant_row_id ON public."IamTenant" USING btree ("rowId");
        `,
        downScript: `
            DROP INDEX IF EXISTS "iam_tenant_row_id";
            ALTER TABLE public."IamTenant" DROP COLUMN IF EXISTS "rowId";
        `,
    },
    {
        id      : 'f1833794-a67c-4e1a-8eaf-3036b4ff2a50',
        name    : 'Add rowId to IamUser',
        version : '0.0.1',
        sort    : 7,
        upScript: `
            ALTER TABLE public."IamUser" ADD COLUMN "rowId" BIGINT GENERATED BY DEFAULT AS IDENTITY;

            WITH ordered AS (
                SELECT id AS uuid_pk, ROW_NUMBER() OVER (ORDER BY "createdAt", id) AS rn FROM public."IamUser"
            )
            UPDATE public."IamUser" t
                SET "rowId" = o.rn
            FROM ordered o
                WHERE t.id = o.uuid_pk
                    AND t."rowId" IS NULL;

            SELECT setval(pg_get_serial_sequence('public."IamUser"','rowId'), (SELECT MAX("rowId") FROM public."IamUser"), true);

            ALTER TABLE public."IamUser" ALTER COLUMN "rowId" SET NOT NULL;
            CREATE UNIQUE INDEX iam_user_row_id ON public."IamUser" USING btree ("rowId");
        `,
        downScript: `
            DROP INDEX IF EXISTS "iam_user_row_id";
            ALTER TABLE public."IamUser" DROP COLUMN IF EXISTS "rowId";
        `,
    },
    {
        id      : '9e39aed3-7ed0-4253-9aa4-0d39a68d4472',
        name    : 'Add rowId to OAuthScope',
        version : '0.0.1',
        sort    : 8,
        upScript: `
            ALTER TABLE public."OAuthScope" ADD COLUMN "rowId" BIGINT GENERATED BY DEFAULT AS IDENTITY;

            WITH ordered AS (
                SELECT id AS uuid_pk, ROW_NUMBER() OVER (ORDER BY "createdAt", id) AS rn FROM public."OAuthScope"
            )
            UPDATE public."OAuthScope" t
                SET "rowId" = o.rn
            FROM ordered o
                WHERE t.id = o.uuid_pk
                    AND t."rowId" IS NULL;

            SELECT setval(pg_get_serial_sequence('public."OAuthScope"','rowId'), (SELECT MAX("rowId") FROM public."OAuthScope"), true);

            ALTER TABLE public."OAuthScope" ALTER COLUMN "rowId" SET NOT NULL;
            CREATE UNIQUE INDEX o_auth_scope_row_id ON public."OAuthScope" USING btree ("rowId");
        `,
        downScript: `
            DROP INDEX IF EXISTS "o_auth_scope_row_id";
            ALTER TABLE public."OAuthScope" DROP COLUMN IF EXISTS "rowId";
        `,
    },
    {
        id      : '23e21696-36a2-431f-a650-7b6922cf1b7a',
        name    : 'Add rowId to OAuthRefreshToken',
        version : '0.0.1',
        sort    : 9,
        upScript: `
            ALTER TABLE public."OAuthRefreshToken" ADD COLUMN "rowId" BIGINT GENERATED BY DEFAULT AS IDENTITY;

            WITH ordered AS (
                SELECT id AS uuid_pk, ROW_NUMBER() OVER (ORDER BY "createdAt", id) AS rn FROM public."OAuthRefreshToken"
            )
            UPDATE public."OAuthRefreshToken" t
                SET "rowId" = o.rn
            FROM ordered o
                WHERE t.id = o.uuid_pk
                    AND t."rowId" IS NULL;

            SELECT setval(pg_get_serial_sequence('public."OAuthRefreshToken"','rowId'), (SELECT MAX("rowId") FROM public."OAuthRefreshToken"), true);

            ALTER TABLE public."OAuthRefreshToken" ALTER COLUMN "rowId" SET NOT NULL;
            CREATE UNIQUE INDEX o_auth_refresh_token_row_id ON public."OAuthRefreshToken" USING btree ("rowId");
        `,
        downScript: `
            DROP INDEX IF EXISTS "o_auth_refresh_token_row_id";
            ALTER TABLE public."OAuthRefreshToken" DROP COLUMN IF EXISTS "rowId";
        `,
    },
    {
        id      : '77835391-a4ef-4e2e-ac0b-999489f947d9',
        name    : 'Add rowId to OAuthClient',
        version : '0.0.1',
        sort    : 10,
        upScript: `
            ALTER TABLE public."OAuthClient" ADD COLUMN "rowId" BIGINT GENERATED BY DEFAULT AS IDENTITY;

            WITH ordered AS (
                SELECT id AS uuid_pk, ROW_NUMBER() OVER (ORDER BY "createdAt", id) AS rn FROM public."OAuthClient"
            )
            UPDATE public."OAuthClient" t
                SET "rowId" = o.rn
            FROM ordered o
                WHERE t.id = o.uuid_pk
                    AND t."rowId" IS NULL;

            SELECT setval(pg_get_serial_sequence('public."OAuthClient"','rowId'), (SELECT MAX("rowId") FROM public."OAuthClient"), true);

            ALTER TABLE public."OAuthClient" ALTER COLUMN "rowId" SET NOT NULL;
            CREATE UNIQUE INDEX o_auth_client_row_id ON public."OAuthClient" USING btree ("rowId");
        `,
        downScript: `
            DROP INDEX IF EXISTS "o_auth_client_row_id";
            ALTER TABLE public."OAuthClient" DROP COLUMN IF EXISTS "rowId";
        `,
    },
    {
        id      : 'f0c95356-442c-4497-8962-2a95088051ba',
        name    : 'Add rowId to OAuthApplication',
        version : '0.0.1',
        sort    : 11,
        upScript: `
            ALTER TABLE public."OAuthApplication" ADD COLUMN "rowId" BIGINT GENERATED BY DEFAULT AS IDENTITY;

            WITH ordered AS (
                SELECT id AS uuid_pk, ROW_NUMBER() OVER (ORDER BY "createdAt", id) AS rn FROM public."OAuthApplication"
            )
            UPDATE public."OAuthApplication" t
                SET "rowId" = o.rn
            FROM ordered o
                WHERE t.id = o.uuid_pk
                    AND t."rowId" IS NULL;

            SELECT setval(pg_get_serial_sequence('public."OAuthApplication"','rowId'), (SELECT MAX("rowId") FROM public."OAuthApplication"), true);

            ALTER TABLE public."OAuthApplication" ALTER COLUMN "rowId" SET NOT NULL;
            CREATE UNIQUE INDEX o_auth_application_row_id ON public."OAuthApplication" USING btree ("rowId");
        `,
        downScript: `
            DROP INDEX IF EXISTS "o_auth_application_row_id";
            ALTER TABLE public."OAuthApplication" DROP COLUMN IF EXISTS "rowId";
        `,
    },
    {
        id      : '0fe540f5-7182-4b72-95f3-6a84f71c3320',
        name    : 'Add rowId to OAuthAccessToken',
        version : '0.0.1',
        sort    : 12,
        upScript: `
            ALTER TABLE public."OAuthAccessToken" ADD COLUMN "rowId" BIGINT GENERATED BY DEFAULT AS IDENTITY;

            WITH ordered AS (
                SELECT id AS uuid_pk, ROW_NUMBER() OVER (ORDER BY "createdAt", id) AS rn FROM public."OAuthAccessToken"
            )
            UPDATE public."OAuthAccessToken" t
                SET "rowId" = o.rn
            FROM ordered o
                WHERE t.id = o.uuid_pk
                    AND t."rowId" IS NULL;

            SELECT setval(pg_get_serial_sequence('public."OAuthAccessToken"','rowId'), (SELECT MAX("rowId") FROM public."OAuthAccessToken"), true);

            ALTER TABLE public."OAuthAccessToken" ALTER COLUMN "rowId" SET NOT NULL;
            CREATE UNIQUE INDEX o_auth_access_token_row_id ON public."OAuthAccessToken" USING btree ("rowId");
        `,
        downScript: `
            DROP INDEX IF EXISTS "o_auth_access_token_row_id";
            ALTER TABLE public."OAuthAccessToken" DROP COLUMN IF EXISTS "rowId";
        `,
    },

    {
        id      : '80946fe2-eb5c-4879-b1a4-ebcbd679dbaf',
        name    : 'Add rowId to ToolsKeyValue',
        version : '0.0.1',
        sort    : 13,
        upScript: `
            ALTER TABLE public."ToolsKeyValue" ADD COLUMN "rowId" BIGINT GENERATED BY DEFAULT AS IDENTITY;

            WITH ordered AS (
                SELECT id AS uuid_pk, ROW_NUMBER() OVER (ORDER BY "createdAt", id) AS rn FROM public."ToolsKeyValue"
            )
            UPDATE public."ToolsKeyValue" t
                SET "rowId" = o.rn
            FROM ordered o
                WHERE t.id = o.uuid_pk
                    AND t."rowId" IS NULL;

            SELECT setval(pg_get_serial_sequence('public."ToolsKeyValue"','rowId'), (SELECT MAX("rowId") FROM public."ToolsKeyValue"), true);

            ALTER TABLE public."ToolsKeyValue" ALTER COLUMN "rowId" SET NOT NULL;
            CREATE UNIQUE INDEX tools_key_value_row_id ON public."ToolsKeyValue" USING btree ("rowId");
        `,
        downScript: `
            DROP INDEX IF EXISTS "tools_key_value_row_id";
            ALTER TABLE public."ToolsKeyValue" DROP COLUMN IF EXISTS "rowId";
        `,
    },
    {
        id      : '854d3d56-e592-4d4e-8ff7-2229f7f5dc6d',
        name    : 'Add rowId to ToolsMigration',
        version : '0.0.1',
        sort    : 14,
        upScript: `
            ALTER TABLE public."ToolsMigration" ADD COLUMN "rowId" BIGINT GENERATED BY DEFAULT AS IDENTITY;

            WITH ordered AS (
                SELECT id AS uuid_pk, ROW_NUMBER() OVER (ORDER BY "createdAt", id) AS rn FROM public."ToolsMigration"
            )
            UPDATE public."ToolsMigration" t
                SET "rowId" = o.rn
            FROM ordered o
                WHERE t.id = o.uuid_pk
                    AND t."rowId" IS NULL;

            SELECT setval(pg_get_serial_sequence('public."ToolsMigration"','rowId'), (SELECT MAX("rowId") FROM public."ToolsMigration"), true);

            ALTER TABLE public."ToolsMigration" ALTER COLUMN "rowId" SET NOT NULL;
            CREATE UNIQUE INDEX tools_migration_row_id ON public."ToolsMigration" USING btree ("rowId");
        `,
        downScript: `
            DROP INDEX IF EXISTS "tools_migration_row_id";
            ALTER TABLE public."ToolsMigration" DROP COLUMN IF EXISTS "rowId";
        `,
    },
    {
        id      : 'a5c36dd5-024f-4282-832a-f7efbc8e4bec',
        name    : 'Add rowId to ToolsProcedure',
        version : '0.0.1',
        sort    : 15,
        upScript: `
            ALTER TABLE public."ToolsProcedure" ADD COLUMN "rowId" BIGINT GENERATED BY DEFAULT AS IDENTITY;

            WITH ordered AS (
                SELECT id AS uuid_pk, ROW_NUMBER() OVER (ORDER BY "createdAt", id) AS rn FROM public."ToolsProcedure"
            )
            UPDATE public."ToolsProcedure" t
                SET "rowId" = o.rn
            FROM ordered o
                WHERE t.id = o.uuid_pk
                    AND t."rowId" IS NULL;

            SELECT setval(pg_get_serial_sequence('public."ToolsProcedure"','rowId'), (SELECT MAX("rowId") FROM public."ToolsProcedure"), true);

            ALTER TABLE public."ToolsProcedure" ALTER COLUMN "rowId" SET NOT NULL;
            CREATE UNIQUE INDEX tools_procedure_row_id ON public."ToolsProcedure" USING btree ("rowId");
        `,
        downScript: `
            DROP INDEX IF EXISTS "tools_procedure_row_id";
            ALTER TABLE public."ToolsProcedure" DROP COLUMN IF EXISTS "rowId";
        `,
    },
];