export enum SqlType
{
    'BOOLEAN'           = 'boolean',
    'CHAR'              = 'char',
    'DATE'              = 'date',
    'DATETIME'          = 'datetime',
    'DECIMAL'           = 'decimal',
    'ENUM'              = 'enum',
    'FLOAT'             = 'float',
    'ID'                = 'id',
    'INT.UNSIGNED'      = 'int.unsigned',
    'INT'               = 'int',
    'JSON'              = 'json',
    'PASSWORD'          = 'password',
    'RELATIONSHIP'      = 'relationship',
    'SMALLINT.UNSIGNED' = 'smallint.unsigned',
    'SMALLINT'          = 'smallint',
    'TEXT'              = 'text',
    'TIMESTAMP'         = 'timestamp',
    'VARCHAR'           = 'varchar',
}